version: "2"
services:
  go-echo:
    build: .
    image: inc-nlp-service-echo
    container_name: inc-nlp-service-echo
    external_links: 
      - postgres
    ports: 
      - 9000:9000
    volumes:
      - ./public:/go/src/inc-nlp-service-echo/public
    environment: 
      - TZ=Asia/Bangkok
      - ENV=heroku
      - ECHO_APP_NAME=inc-nlp-service-echo
      - PORT=9000
      - ECHO_LOG_LEVEL=INFO
      - NLP_DB_DIALECTS=postgres
      - NLP_DB_NAME=postgres
      - NLP_DB_HOST=postgres
      - NLP_DB_PORT=5432
      - NLP_DB_USERNAME=postgres
      - NLP_DB_PASSWORD=
      - IS_SWAGGER=true
    command: 
      - /go/src/inc-nlp-service-echo/inc-nlp-service-echo