version: "2"
services:
  go-echo:
    build: .
    image: inc-nlp-service-echo
    container_name: inc-nlp-service-echo
    external_links:
      - postgres
    ports: 
      - 9000:9000
    environment: 
      - TZ=Asia/Bangkok
      - ENV=heroku
      - ECHO_APP_NAME=inc-nlp-service-echo
      - PORT=9000
      - ECHO_LOG_LEVEL=INFO 
      - NLP_DB_DIALECTS=postgres
      - NLP_DB_NAME=reaxllzt
      - NLP_DB_HOST=john.db.elephantsql.com
      - NLP_DB_PORT=5432
      - NLP_DB_USERNAME=reaxllzt
      - NLP_DB_PASSWORD=qs0jZQMUWFOvQU4SaYXElVegjzDgLz7c
      - KAFKA_BROKERS=moped-01.srvs.cloudkafka.com:9094,moped-02.srvs.cloudkafka.com:9094,moped-03.srvs.cloudkafka.com:9094
      - KAFKA_USERNAME=60vh9kjz
      - KAFKA_PASSWORD=iMkMvCgioCShnTCAdsrDBLe0IdsM6RDF
      - KAFKA_TOPIC_PREFIX=60vh9kjz-
      - KAFKA_GROUP_ID=CLOUDKARAFKA_GROUPID
      - IS_SWAGGER=true
    command:
      - ./inc-nlp-service-echo