// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domains "inc-nlp-service-echo/business_module/domains"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/satori/go.uuid"
)

// IAppRepository is an autogenerated mock type for the IAppRepository type
type IAppRepository struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ID
func (_m *IAppRepository) FindByID(ID uuid.UUID) domains.AppDomain {
	ret := _m.Called(ID)

	var r0 domains.AppDomain
	if rf, ok := ret.Get(0).(func(uuid.UUID) domains.AppDomain); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(domains.AppDomain)
	}

	return r0
}
