// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	domains "inc-nlp-service-echo/business_module/domains"

	gorm "github.com/jinzhu/gorm"

	mock "github.com/stretchr/testify/mock"

	uuid "github.com/satori/go.uuid"
)

// IClientRepository is an autogenerated mock type for the IClientRepository type
type IClientRepository struct {
	mock.Mock
}

// FindByID provides a mock function with given fields: ID
func (_m *IClientRepository) FindByID(ID uuid.UUID) domains.ClientDomain {
	ret := _m.Called(ID)

	var r0 domains.ClientDomain
	if rf, ok := ret.Get(0).(func(uuid.UUID) domains.ClientDomain); ok {
		r0 = rf(ID)
	} else {
		r0 = ret.Get(0).(domains.ClientDomain)
	}

	return r0
}

// Save provides a mock function with given fields: Domain
func (_m *IClientRepository) Save(Domain *domains.ClientDomain) *gorm.DB {
	ret := _m.Called(Domain)

	var r0 *gorm.DB
	if rf, ok := ret.Get(0).(func(*domains.ClientDomain) *gorm.DB); ok {
		r0 = rf(Domain)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*gorm.DB)
		}
	}

	return r0
}
